### ISSUE TITLE
Fix TravisCI Build Errors

### ISSUE THREAD

**Issue by dligthart** [TEDxAmsterdam/Backend#4]
- Exclude node_modules from jshint . (only own code)

https://travis-ci.org/TEDxAmsterdam/Backend/

**Comment by ghost** [comment]
Will look into it.

**Comment by dligthart** [comment]
$ node --version
v4.0.0
$ npm --version
2.14.2
$ nvm --version
0.31.0
install
27.48s$ npm install 
serve-favicon@2.3.0 node_modules/serve-favicon
├── fresh@0.3.0
├── parseurl@1.3.1
├── ms@0.7.1
└── etag@1.7.0
parse-database-url@0.3.0 node_modules/parse-database-url
└── mongodb-uri@0.9.7
cors@2.7.1 node_modules/cors
└── vary@1.1.0
compression@1.6.1 node_modules/compression
├── on-headers@1.0.1
├── vary@1.1.0
├── bytes@2.2.0
├── debug@2.2.0 (ms@0.7.1)
├── compressible@2.0.7 (mime-db@1.22.0)
└── accepts@1.3.2 (negotiator@0.6.0, mime-types@2.1.10)
helmet@0.14.0 node_modules/helmet
├── ienoopen@0.1.0
├── dont-sniff-mimetype@0.1.0
├── hide-powered-by@0.1.0
├── helmet-crossdomain@0.1.0
├── nocache@0.4.0
├── hpkp@0.2.0
├── x-xss-protection@0.2.0
├── depd@1.1.0
├── frameguard@0.2.2 (lodash.isstring@3.0.1)
├── hsts@0.2.0 (core-util-is@1.0.1)
├── connect@3.4.0 (parseurl@1.3.1, utils-merge@1.0.0, debug@2.2.0, finalhandler@0.4.0)
└── helmet-csp@0.3.0 (lodash.isstring@3.0.1, camelize@1.0.0, platform@1.3.0, content-security-policy-builder@0.2.0, lodash.pick@3.1.0)
loopback-connector-mysql@2.2.1 node_modules/loopback-connector-mysql
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── loopback-connector@2.3.0 (async@1.5.2)
└── mysql@2.10.2 (readable-stream@1.1.13, bignumber.js@2.1.4)
logfmt@1.2.0 node_modules/logfmt
├── split@0.2.10
├── through@2.3.8
└── lodash@2.4.2
loopback-component-oauth2@2.4.0 node_modules/loopback-component-oauth2
├── uid2@0.0.3
├── utils-merge@1.0.0
├── passport-strategy@1.0.0
├── connect-ensure-login@0.1.1
├── passport-oauth2-client-password@0.1.2
├── passport-http-bearer@1.0.1
├── passport-local@1.0.0
├── passport-http@0.3.0
├── pkginfo@0.4.0
├── debug@2.2.0 (ms@0.7.1)
├── path-to-regexp@1.2.1 (isarray@0.0.1)
├── passport@0.3.2 (pause@0.0.1)
├── async@1.5.2
└── jws@3.1.3 (jwa@1.1.3, base64url@1.0.6)
loopback-datasource-juggler@2.46.0 node_modules/loopback-datasource-juggler
├── depd@1.1.0
├── inflection@1.9.0
├── node-uuid@1.4.7
├── qs@3.1.0
├── async@1.0.0
├── debug@2.2.0 (ms@0.7.1)
├── traverse@0.6.6
└── loopback-connector@2.3.0
loopback-boot@2.18.0 node_modules/loopback-boot
├── commondir@0.0.1
├── toposort@0.2.12
├── async@0.9.2
├── debug@2.2.0 (ms@0.7.1)
├── semver@4.3.6
└── lodash@3.10.1
nsp@2.3.0 node_modules/nsp
├── path-is-absolute@1.0.0
├── semver@5.1.0
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, has-ansi@2.0.0, strip-ansi@3.0.1)
├── subcommand@2.0.3 (xtend@4.0.1, cliclopts@1.1.1, minimist@1.2.0, debug@2.2.0)
├── rc@1.1.6 (ini@1.3.4, strip-json-comments@1.0.4, deep-extend@0.4.1, minimist@1.2.0)
├── cli-table@0.3.1 (colors@1.0.3)
├── https-proxy-agent@1.0.0 (extend@3.0.0, debug@2.2.0, agent-base@2.0.1)
├── wreck@6.3.0 (boom@2.10.1, hoek@2.16.3)
├── nodesecurity-npm-utils@4.0.1 (silent-npm-registry-client@2.0.0)
└── joi@6.10.1 (topo@1.1.0, isemail@1.2.0, hoek@2.16.3, moment@2.12.0)
jshint@2.9.1 node_modules/jshint
├── strip-json-comments@1.0.4
├── exit@0.1.2
├── console-browserify@1.1.0 (date-now@0.1.4)
├── shelljs@0.3.0
├── minimatch@2.0.10 (brace-expansion@1.1.3)
├── cli@0.6.6 (glob@3.2.11)
├── htmlparser2@3.8.3 (domelementtype@1.3.0, entities@1.0.0, domhandler@2.3.0, readable-stream@1.1.13, domutils@1.5.1)
└── lodash@3.7.0
loopback-component-explorer@2.4.0 node_modules/loopback-component-explorer
├── debug@2.2.0 (ms@0.7.1)
├── loopback-swagger@2.4.1 (async@1.5.2, ejs@1.0.0, underscore.string@2.3.3)
├── lodash@3.10.1
└── strong-swagger-ui@21.0.2
slack@6.1.0 node_modules/slack
├── query-string@3.0.3 (strict-uri-encode@1.1.0)
├── ws@1.1.0 (options@0.0.6, ultron@1.0.2)
├── httpplease@0.16.4 (xtend@3.0.0, xmlhttprequest@1.8.0, urllite@0.5.0)
├── request@2.70.0 (is-typedarray@1.0.0, aws-sign2@0.6.0, forever-agent@0.6.1, caseless@0.11.0, stringstream@0.0.5, tunnel-agent@0.4.2, oauth-sign@0.8.1, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, combined-stream@1.0.5, qs@6.1.0, mime-types@2.1.10, tough-cookie@2.2.2, aws4@1.3.2, form-data@1.0.0-rc4, bl@1.1.2, har-validator@2.0.6, http-signature@1.1.1, hawk@3.1.3)
└── lodash@4.10.0
async@2.0.0-rc.3 node_modules/async
└── lodash@4.10.0
loopback@2.27.0 node_modules/loopback
├── uid2@0.0.3
├── nodemailer-stub-transport@0.1.5
├── stable@0.1.5
├── canonical-json@0.0.4
├── depd@1.1.0
├── inflection@1.9.0
├── loopback-phase@1.3.0
├── async@0.9.2
├── loopback-connector-remote@1.2.0
├── debug@2.2.0 (ms@0.7.1)
├── cookie-parser@1.4.1 (cookie-signature@1.0.6, cookie@0.2.3)
├── bcryptjs@2.3.0
├── ejs@2.4.1
├── errorhandler@1.4.3 (escape-html@1.0.3, accepts@1.3.2)
├── body-parser@1.15.0 (bytes@2.2.0, content-type@1.0.1, on-finished@2.3.0, raw-body@2.1.6, http-errors@1.4.0, qs@6.1.0, type-is@1.6.12, iconv-lite@0.4.13)
├── continuation-local-storage@3.1.6 (emitter-listener@1.0.1, async-listener@0.5.8)
├── underscore.string@3.3.4 (util-deprecate@1.0.2, sprintf-js@1.0.3)
├── express@4.13.4 (escape-html@1.0.3, utils-merge@1.0.0, cookie-signature@1.0.6, fresh@0.3.0, parseurl@1.3.1, array-flatten@1.1.1, content-type@1.0.1, etag@1.7.0, merge-descriptors@1.0.1, methods@1.1.2, range-parser@1.0.3, vary@1.0.1, path-to-regexp@0.1.7, cookie@0.1.5, content-disposition@0.5.1, serve-static@1.10.2, on-finished@2.3.0, finalhandler@0.4.1, qs@4.0.0, proxy-addr@1.0.10, send@0.13.1, type-is@1.6.12, accepts@1.2.13)
├── nodemailer@1.11.0 (nodemailer-direct-transport@1.1.0, nodemailer-smtp-transport@1.1.0, libmime@1.2.0, needle@0.11.0, mailcomposer@2.1.0)
└── strong-remoting@2.26.0 (eventemitter2@0.4.14, qs@2.4.2, js2xmlparser@0.1.9, traverse@0.6.6, sse@0.0.6, mux-demux@3.7.9, request@2.70.0, jayson@1.2.2, xml2js@0.4.16)
$ npm test

> tedxapi@1.0.0 pretest /home/travis/build/TEDxAmsterdam/Backend
> jshint .
> client/public/lib/loadSwaggerUI.js: line 1, col 1, Use the function form of "use strict".
> client/public/lib/loadSwaggerUI.js: line 76, col 28, 'SwaggerClient' is not defined.
> client/public/lib/loadSwaggerUI.js: line 115, col 7, 'console' is not defined.
> client/public/lib/loadSwaggerUI.js: line 115, col 25, 'console' is not defined.
> node_modules/async/apply.js: line 1, col 1, Use the function form of "use strict".
> node_modules/async/apply.js: line 14, col 31, Bad invocation.
> node_modules/async/apply.js: line 13, col 38, Bad invocation.
> node_modules/async/apply.js: line 3, col 23, 'exports' is not defined.
> node_modules/async/apply.js: line 13, col 1, 'exports' is not defined.
> node_modules/async/apply.js: line 18, col 18, 'exports' is not defined.
> node_modules/async/apply.js: line 7, col 13, 'require' is not defined.
> node_modules/async/apply.js: line 18, col 1, 'module' is not defined.
> ...

**Comment by dligthart** [comment]
Was able to reduce to 19 errors:

> tedxapi@1.0.0 pretest /home/travis/build/TEDxAmsterdam/Backend
> jshint --exclude ./node_modules .
> client/public/lib/loadSwaggerUI.js: line 1, col 1, Use the function form of "use strict".
> client/public/lib/loadSwaggerUI.js: line 76, col 28, 'SwaggerClient' is not defined.
> client/public/lib/loadSwaggerUI.js: line 115, col 7, 'console' is not defined.
> client/public/lib/loadSwaggerUI.js: line 115, col 25, 'console' is not defined.
> server/boot/init-data.js: line 49, col 32, Don't make functions within a loop.
> server/boot/init-data.js: line 83, col 32, Don't make functions within a loop.
> server/boot/init-data.js: line 102, col 32, Don't make functions within a loop.
> server/boot/init-data.js: line 116, col 34, Don't make functions within a loop.
> server/components/create-admin.js: line 18, col 16, Missing '()' invoking a constructor.
> server/components/create-admin.js: line 29, col 40, ['Author'] is better written in dot notation.
> server/components/create-admin.js: line 92, col 52, ['User'] is better written in dot notation.
> server/components/create-admin.js: line 101, col 59, ['AccessToken'] is better written in dot notation.
> server/components/redis-adapter.js: line 3, col 29, Missing semicolon.
> server/components/redis-adapter.js: line 9, col 19, Unnecessary semicolon.
> server/components/redis-adapter.js: line 61, col 2, Missing semicolon.
> server/components/redis-adapter.js: line 66, col 2, Missing semicolon.
> server/components/redis-adapter.js: line 89, col 2, Missing semicolon.
> server/components/redis-adapter.js: line 107, col 2, Missing semicolon.
> server/components/redis-adapter.js: line 119, col 2, Missing semicolon.
> 19 errors
> npm ERR! Test failed.  See above for more details.

**Comment by dligthart** [comment]
Fixed using jshintc
